# Generated by Django 5.0 on 2023-12-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='types',
            field=models.CharField(choices=[('R', 'Records'), ('C', 'Clothing'), ('P', 'Posters'), ('M', 'Misc')], max_length=15),
        ),
    ]
