# Generated by Django 5.0 on 2023-12-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
    ]
